export const SEED_PREFIX = "semana8";

export const SEED_SERVICES = [
  {
    seedKey: `${SEED_PREFIX}:consulta-clinica`,
    name: "Consulta clínica",
    description: "Control general de 30 minutos",
    duration: 30,
    price: 15000,
    category: "salud",
    available: true,
  },
  {
    seedKey: `${SEED_PREFIX}:limpieza-dental`,
    name: "Limpieza dental",
    description: "Higiene y revisión odontológica",
    duration: 45,
    price: 22000,
    category: "salud",
    available: true,
  },
  {
    seedKey: `${SEED_PREFIX}:control-pediatrico`,
    name: "Control pediátrico",
    description: "Consulta de seguimiento infantil",
    duration: 25,
    price: 18000,
    category: "salud",
    available: true,
  },
  {
    seedKey: `${SEED_PREFIX}:nutricion`,
    name: "Consulta nutricional",
    description: "Plan alimentario y control",
    duration: 40,
    price: 20000,
    category: "salud",
    available: true,
  },
  {
    seedKey: `${SEED_PREFIX}:psicologia`,
    name: "Consulta psicológica",
    description: "Sesión individual de 50 minutos",
    duration: 50,
    price: 24000,
    category: "salud",
    available: true,
  },
  {
    seedKey: `${SEED_PREFIX}:corte-barba`,
    name: "Corte + barba",
    description: "Servicio de estética para cabello y barba",
    duration: 40,
    price: 12000,
    category: "estetica",
    available: true,
  },
  {
    seedKey: `${SEED_PREFIX}:coloracion`,
    name: "Coloración",
    description: "Color completo con tratamiento",
    duration: 90,
    price: 25000,
    category: "estetica",
    available: true,
  },
  {
    seedKey: `${SEED_PREFIX}:manicura`,
    name: "Manicura",
    description: "Limpieza y esmaltado",
    duration: 30,
    price: 8000,
    category: "estetica",
    available: false,
  },
  {
    seedKey: `${SEED_PREFIX}:depilacion`,
    name: "Depilación",
    description: "Sesión de 35 minutos",
    duration: 35,
    price: 16000,
    category: "estetica",
    available: true,
  },
  {
    seedKey: `${SEED_PREFIX}:masaje`,
    name: "Masaje descontracturante",
    description: "Sesión de 60 minutos",
    duration: 60,
    price: 28000,
    category: "bienestar",
    available: false,
  },
  {
    seedKey: `${SEED_PREFIX}:yoga`,
    name: "Clase de yoga",
    description: "Práctica grupal de 50 minutos",
    duration: 50,
    price: 9000,
    category: "bienestar",
    available: true,
  },
  {
    seedKey: `${SEED_PREFIX}:entrenamiento`,
    name: "Entrenamiento funcional",
    description: "Sesión guiada de 55 minutos",
    duration: 55,
    price: 11000,
    category: "bienestar",
    available: true,
  },
];

export const SEED_BOOKINGS = [
  {
    seedKey: `${SEED_PREFIX}:reserva-laura`,
    clientName: "Laura Pérez",
    clientEmail: "laura@example.com",
    date: "2026-09-10",
    time: "10:00",
    status: "confirmed",
    serviceKeys: [`${SEED_PREFIX}:consulta-clinica`, `${SEED_PREFIX}:yoga`],
  },
  {
    seedKey: `${SEED_PREFIX}:reserva-vacia`,
    clientName: "Martín Soto",
    clientEmail: "martin@example.com",
    date: "2026-09-12",
    time: "16:30",
    status: "pending",
    serviceKeys: [],
  },
];
